import type { Metadata } from "next";
import { Roboto_Condensed as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { MainNavigation } from "@/components/main-nav";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen max-w-6xl mx-auto px-2 lg:px-4 bg-white font-sans antialiased",
					fontSans.variable
				)}
			>
				<MainNavigation />
				{children}
			</body>
		</html>
	);
}
